version: "3.7"

services:
  react-app:
    build: ./frontend
    container_name: react-app
    ports:
      - "3007:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nest-app
    networks:
      - crystal-network

  nest-app:
    build: ./backend
    container_name: nest-app
    ports:
      - "3005:3005"
      - "3006:3006"
    volumes:
      - ./frontend/build:/app/public # Mount frontend build directory
    networks:
      - crystal-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27019:27017"
    networks:
      - crystal-network

networks:
  crystal-network:
    driver: bridge